export const ADD_PATIENT_REQ = "ADD_PATIENT_REQ";
export const ADD_PATIENT_REQ_SUCCESS = "ADD_PATIENT_REQ_SUCCESS";
export const ADD_PATIENT_REQ_FAILURE = "ADD_PATIENT_REQ_FAILURE";

export const GET_PATIENTS_REQ = "GET_PATIENTS_REQ";
export const GET_PATIENTS_REQ_SUCCESS = "GET_PATIENTS_REQ_SUCCESS";
export const GET_PATIENTS_REQ_FAILURE = "GET_PATIENTS_REQ_FAILURE";

export const GET_PATIENTS_BY_NAME_REQ = "GET_PATIENTS_BY_NAME_REQ";
export const GET_PATIENTS_BY_NAME_REQ_SUCCESS =
  "GET_PATIENTS_BY_NAME_REQ_SUCCESS";
export const GET_PATIENTS_BY_NAME_REQ_FAILURE =
  "GET_PATIENTS_BY_NAME_REQ_FAILURE";

export const GET_PATIENT_BY_ID_REQ = "GET_PATIENT_BY_ID_REQ";
export const GET_PATIENT_BY_ID_REQ_SUCCESS = "GET_PATIENT_BY_ID_REQ_SUCCESS";
export const GET_PATIENT_BY_ID_REQ_FAILURE = "GET_PATIENT_BY_ID_REQ_FAILURE";
