export const SIGNUP_REQ = "SIGNUP_REQ";
export const SIGNUP_REQ_SUCCESS = "SIGNUP_REQ_SUCCESS";
export const SIGNUP_REQ_FAILURE = "SIGNUP_REQ_FAILURE";

export const LOGIN_REQ = "LOGIN_REQ";
export const LOGIN_REQ_SUCCESS = "LOGIN_REQ_SUCCESS";
export const LOGIN_REQ_FAILURE = "LOGIN_REQ_FAILURE";

export const LOGOUT_REQ = "LOGOUT_REQ";

export const GET_ALL_DOCTORS_REQ = "GET_ALL_DOCTORS_REQ";
export const GET_ALL_DOCTORS_REQ_SUCCESS = "GET_ALL_DOCTORS_REQ_SUCCESS";
export const GET_ALL_DOCTORS_REQ_FAILURE = "GET_ALL_DOCTORS_REQ_FAILURE";
